version: '3.8'
services:
  marcosilva-dev-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - net
    environment:
      - NEXTJS_CONTACT_WEBHOOK_URL=${NEXTJS_CONTACT_WEBHOOK_URL}
      - NEXTJS_CONTACT_WEBHOOK_HEADERS=${NEXTJS_CONTACT_WEBHOOK_HEADERS}
networks:
  net:
    driver: bridge
